### ISSUE TITLE
Keyboard hiding set value which are in bottom

### ISSUE THREAD

**Issue by Rushizzz** [ronit-khalate/Lift#57]
https://github.com/user-attachments/assets/050e9fc1-280b-44e9-81a1-de1861990ed3

- when you try to set values of exercises which are in bottom keyboard pops up and that table becomes completed invisible from view point.
- Please make sure to use zoom or scroll function for it

**Comment by ronit-khalate** [comment]
on it

**Comment by ronit-khalate** [comment]
issue is not visible in todo chart

**Comment by ronit-khalate** [comment]
add it in in progress and assign it to me

**Comment by ronit-khalate** [comment]
https://github.com/user-attachments/assets/cfdd266e-b239-4d54-b752-07b7e0227a2b

 take look at it!!!

for last log we need to scroll little bit  is it ok
